### ISSUE TITLE
Unable to autowire SerializerInterface

### ISSUE THREAD

**Issue by rpanfili** [solid-o/symfony#1]
At the moment Symfony is unable to autowire an argument that references the interface `Solido\Symfony\Serialization\SerializerInterface`. 

The only way to get it working is by creating an explicit alias to the existing `solido.serializer` service in this way:
```yaml
---
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Solido\Symfony\Serialization\SerializerInterface: '@solido.serializer'
```
